name: multievent
on:
    push:
        branches:
            - master
            - dev
    pull_request:
        branches:
            - master

jobs:
    test_multievent:
        runs-on: ubuntu-latest
        steps:
            - name: "Echo Basic information"
              run: |
                echo "REF: $GITHUB_REF"
                echo "JOB ID: $GITHUB_JOB"
                echo "Action: $GITHUB_ACTION"
                echo "Actor: $GITHUB_ACTOR"
